import {
  REPLAY_DECISION_HARNESS_WORKER_V10_SUCCESSOR_PROCESS_LAUNCH_INTENT_POLICY_VERSION,
  REPLAY_DECISION_HARNESS_WORKER_V10_SUCCESSOR_PROCESS_LAUNCH_INTENT_SCHEMA_VERSION,
  createReplayDecisionHarnessWorkerV10SuccessorProcessLaunchIntent,
  replayDecisionHarnessWorkerV10SuccessorProcessLaunchIntentKey,
  type ReplayDecisionHarnessWorkerV10SuccessorProcessLaunchIntent,
} from "../../../contracts/src/lib/replay-decision-harness-worker-v10-successor-process-launch-intent"
import type {
  ReplayWorkerV10SuccessorProcessLaunchIntentRegistryInput,
  ReplayWorkerV10SuccessorProcessLaunchIntentSources,
} from "./replay-worker-v10-successor-process-launch-intent-types"

export function buildReplayWorkerV10SuccessorProcessLaunchIntent(
  input: ReplayWorkerV10SuccessorProcessLaunchIntentRegistryInput,
  sources: ReplayWorkerV10SuccessorProcessLaunchIntentSources,
): ReplayDecisionHarnessWorkerV10SuccessorProcessLaunchIntent {
  const parent = sources.command
  const command = parent.successor_execution_admission_command
  const execution = sources.execution
  const transport = execution.successor_artifact_bound_transport_contract
  const stdio = sources.stdio.successor_stdio_artifact_evidence
  const clock = input.post_command_clock_attestation
  const receipt = input.post_command_registry_read_receipt
  const observation = input.post_command_lease_observation
  const key = replayDecisionHarnessWorkerV10SuccessorProcessLaunchIntentKey({
    source_execution_admission_command_hash: command.command_hash,
    target_worker_request_hash: parent.target_worker_request_hash,
    attempt_id: parent.attempt_id,
    worker_id: parent.worker_id,
    lease_generation: parent.successor_lease_generation,
    intent_policy_version:
      REPLAY_DECISION_HARNESS_WORKER_V10_SUCCESSOR_PROCESS_LAUNCH_INTENT_POLICY_VERSION,
  })
  return createReplayDecisionHarnessWorkerV10SuccessorProcessLaunchIntent({
    schema_version: REPLAY_DECISION_HARNESS_WORKER_V10_SUCCESSOR_PROCESS_LAUNCH_INTENT_SCHEMA_VERSION,
    intent_id: `decision-harness-worker-v10-successor-intent-${key.slice(0, 24)}`,
    intent_ref: `intent://replay-decision-harness-worker-v10-successor/${key.slice(0, 24)}`,
    intent_key: key,
    intent_policy_version:
      REPLAY_DECISION_HARNESS_WORKER_V10_SUCCESSOR_PROCESS_LAUNCH_INTENT_POLICY_VERSION,
    scope: "one_successor_command_bound_non_executable_process_launch_intent",
    owner: "replay_runner_worker_v10_successor_process_launch_intent_registry",
    purpose: "freeze_runtime_artifact_and_post_command_lease_evidence_before_capsule_derivation",
    status: "successor_intent_committed_capsule_revalidation_and_process_not_materialized",
    source_successor_execution_command_admission_hash: parent.admission_hash,
    source_parent_canonical_file_sha256: sources.command_file_sha256,
    source_successor_execution_contract_admission_hash: execution.admission_hash,
    source_execution_contract_parent_canonical_file_sha256: sources.execution_file_sha256,
    source_successor_stdio_probe_admission_hash: sources.stdio.admission_hash,
    source_stdio_probe_parent_canonical_file_sha256: sources.stdio_file_sha256,
    source_execution_admission_command_hash: command.command_hash,
    source_execution_admission_contract_hash: parent.source_execution_admission_contract_hash,
    source_artifact_bound_transport_contract_hash:
      parent.source_artifact_bound_transport_contract_hash,
    source_dispatch_claim_hash: parent.successor_dispatch_claim_hash,
    source_stdio_capability_hash: sources.stdio.successor_stdio_capability_hash,
    source_execution_envelope_hash: transport.source_successor_execution_envelope_hash,
    post_command_clock_attestation_hash: clock.attestation_hash,
    post_command_clock_attestation: structuredClone(clock),
    target_logical_request_id: parent.target_logical_request_id,
    target_worker_request_hash: parent.target_worker_request_hash,
    target_worker_request_execution_admission: parent.target_worker_request_execution_admission,
    target_worker_request_transport_status: parent.target_worker_request_transport_status,
    attempt_id: parent.attempt_id,
    attempt_ordinal: parent.attempt_ordinal,
    worker_id: parent.worker_id,
    lease_generation: parent.successor_lease_generation,
    current_attempt_status: "running",
    current_attempt_lease_hash: receipt.current_attempt_lease_hash,
    post_command_lease_observation_hash: observation.observation_hash,
    post_command_registry_read_receipt_hash: receipt.receipt_hash,
    source_command_issued_at: command.issued_at,
    source_command_valid_before: command.valid_before,
    intent_issued_at: clock.registry_read_completed_at,
    valid_before: receipt.current_attempt_lease.lease_expires_at,
    intent_time_semantics: "fresh_post_command_control_plane_clock_completion_not_local_commit_time",
    natural_key_policy: "one_process_launch_intent_per_exact_successor_command",
    post_command_revalidation: "entire_current_attempt_read_starts_after_successor_command_issuance",
    cancellation_revalidation: "control_plane_current_attempt_remains_running_at_revalidation",
    fencing_revalidation: "exact_command_attempt_worker_generation_and_lease_hash_remain_current",
    revalidation_race_limit: "intent_is_non_executable_and_spawn_boundary_must_revalidate_again",
    runtime_id: "bun",
    runtime_version: stdio.runtime.runtime_version,
    runtime_executable_hash: stdio.runtime.executable_sha256,
    process_artifact_hash: stdio.artifact.sha256,
    process_artifact_file_name: stdio.artifact.file_name,
    process_model: "fresh_single_request_process_no_pool_keepalive_or_multiplex",
    artifact_materialization_policy: "ephemeral_private_file_mode_0500_hash_verified_before_spawn",
    spawn_argv_policy: "attested_runtime_then_ephemeral_exact_successor_artifact_only",
    base_environment_policy: "tz_utc_lang_c_lc_all_c_no_inherited_values",
    working_directory_policy: "fresh_private_ephemeral_directory",
    timeout_ms: transport.timeout_ms,
    max_request_frame_bytes: transport.max_request_frame_bytes,
    max_response_frame_bytes: transport.max_response_frame_bytes,
    launch_slot_policy: "one_immutable_intent_per_successor_command_no_automatic_replacement",
    orphan_intent_policy: "intent_without_capsule_revalidation_and_receipt_never_proves_process_start",
    process_launch_authority: "not_granted_until_capsule_and_fresh_spawn_boundary_revalidation",
    required_response_echo_fields: ["execution_admission_command_hash", "worker_request_hash"],
    successor_execution_admission_command_count: 1,
    successor_process_launch_intent_count: 1,
    successor_authority_capsule_count: 0,
    successor_spawn_revalidation_count: 0,
    successor_worker_process_count: 0,
    successor_worker_request_frame_count: 0,
    successor_worker_request_decode_count: 0,
    second_response_count: 0,
    second_schedule_admission_count: 0,
    reproducibility_pair_count: 0,
    harness_receipt_count: 0,
    blocker_set_policy: "complete_deterministic_ordered_post_successor_intent_blockers",
    blockers: ["successor_authority_capsule_not_materialized",
      "successor_spawn_boundary_revalidation_not_materialized",
      "successor_worker_process_and_request_dispatch_not_materialized",
      "second_response_schedule_pair_and_harness_receipt_not_materialized"],
    process_launch_occurrence: "not_materialized",
    dispatch_occurrence: "not_materialized",
    transport_activation: "intent_issued_capsule_and_spawn_blocked",
    harness_invocation: "forbidden",
    response_admission: "not_granted",
    decision_output_authority: "first_schedule_matched_claim_only_successor_intent_committed",
    signal_authority: "none",
    order_authority: "none",
    economic_authority: "none",
    trial_authority: "none",
  })
}
