#!/usr/bin/env python3
"""
Compute, check, or regenerate the Owner Postgres chain's affected-crate table.

`scripts/ci/plan.sh` skips the Owner Postgres chain for a changed crate only when that crate
provably cannot affect it: it is outside the transitive dependency closure of every "Owner root"
crate (`scripts/ci/test-rd-owner-postgres.bash`'s own `guarded_roots` array, read from that file
directly here rather than duplicated, so the two can never drift silently). The closure is every
root itself, plus every crate a root depends on - normal, dev, or build - transitively: a dev
dependency is included too, because this errs toward *more* crates being "in" the closure
(`plan.sh`'s own bias is "run the chain when in doubt," never the other way).

Computing this closure needs `cargo metadata`'s full resolved graph, which needs network and a
warm registry cache - unsuitable for the small, sandboxed `plan` job that reads the committed
table this script writes (`scripts/ci/owner-chain-crates.tsv`) instead. Something that already
pays for a Rust toolchain and a warm cache must keep that table honest: `--check` recomputes the
closure and fails loudly on any difference from the committed table, run from `rust-tests-linux-x86`
(gated the same way the table's consumer is, by `run-rust-tests`, so it only runs when a `.rs` or
`Cargo.toml`/`Cargo.lock` change could have moved a crate across the line).

Usage:
    python3 owner-chain-closure.py --check    # fails (and prints a diff) if the table is stale
    python3 owner-chain-closure.py --write    # regenerates the table in place

"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
CHAIN_SCRIPT = REPO_ROOT / "scripts" / "ci" / "test-rd-owner-postgres.bash"
TABLE_PATH = REPO_ROOT / "scripts" / "ci" / "owner-chain-crates.tsv"
TABLE_HEADER = (
    "# generated by scripts/ci/owner-chain-closure.py --write; do not hand-edit.\n"
    '# <crate-dir>\\t<in|out> - "in" means a change there can reach the Owner Postgres chain\n'
    "# (scripts/ci/test-rd-owner-postgres.bash's guarded_roots, or something a root depends on,\n"
    "# directly or transitively, including dev/build dependencies).\n"
)


def tool(name: str) -> str:
    """
    Resolve a required tool, or say that nothing here can be measured without it.
    """
    found = shutil.which(name)
    if found is None:
        sys.exit(
            f"ERROR: {name} is not on PATH, so the Owner-chain closure cannot be computed.",
        )
    return found


def guarded_root_dirs() -> list[str]:
    """
    Read `guarded_roots` straight out of the chain script.

    So this can never list a different set of roots than the chain itself runs.

    """
    text = CHAIN_SCRIPT.read_text()
    match = re.search(r"readonly guarded_roots=\((.*?)\)", text, re.DOTALL)
    if not match:
        sys.exit(f"could not find 'readonly guarded_roots=(...)' in {CHAIN_SCRIPT}")
    dirs = [line.strip() for line in match.group(1).splitlines()]
    dirs = [d for d in dirs if d and not d.startswith("#")]
    if not dirs:
        sys.exit(f"guarded_roots in {CHAIN_SCRIPT} parsed empty")
    return dirs


def cargo_metadata(*extra_args: str) -> dict:
    """
    Run `cargo metadata` and parse its JSON.
    """
    raw = subprocess.run(
        [tool("cargo"), "metadata", "--format-version", "1", "--locked", *extra_args],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return json.loads(raw)


def crate_dir_of(pkg: dict, workspace_root: str) -> str:
    manifest = pkg["manifest_path"]
    prefix = workspace_root + "/"
    manifest = manifest.removeprefix(prefix)
    return manifest.rsplit("/", 1)[0]


def compute_closure(root_dirs: list[str]) -> list[str]:
    """
    Compute every workspace crate directory in the closure, sorted.
    """
    metadata = cargo_metadata()
    members = set(metadata["workspace_members"])
    packages = {pkg["id"]: pkg for pkg in metadata["packages"] if pkg["id"] in members}
    workspace_root = metadata["workspace_root"]

    dir_to_id = {crate_dir_of(pkg, workspace_root): pkg_id for pkg_id, pkg in packages.items()}
    id_to_dir = {pkg_id: crate_dir_of(pkg, workspace_root) for pkg_id, pkg in packages.items()}
    nodes = {node["id"]: node for node in metadata["resolve"]["nodes"] if node["id"] in members}

    missing = [d for d in root_dirs if d not in dir_to_id]
    if missing:
        sys.exit(f"guarded root(s) not found by `cargo metadata`: {missing}")

    closure_ids = {dir_to_id[d] for d in root_dirs}
    stack = list(closure_ids)
    while stack:
        pkg_id = stack.pop()
        node = nodes.get(pkg_id)
        if node is None:
            continue
        for dep in node.get("deps", []):
            dep_id = dep.get("pkg")
            if dep_id in members and dep_id not in closure_ids:
                closure_ids.add(dep_id)
                stack.append(dep_id)

    return sorted(id_to_dir[pkg_id] for pkg_id in closure_ids)


def all_workspace_crate_dirs() -> list[str]:
    metadata = cargo_metadata("--no-deps")
    members = set(metadata["workspace_members"])
    workspace_root = metadata["workspace_root"]
    return [
        crate_dir_of(pkg, workspace_root) for pkg in metadata["packages"] if pkg["id"] in members
    ]


def render_table(all_dirs: list[str], closure_dirs: set[str]) -> str:
    lines = [TABLE_HEADER]
    lines.extend(
        f"{crate_dir}\t{'in' if crate_dir in closure_dirs else 'out'}\n"
        for crate_dir in sorted(all_dirs)
    )
    return "".join(lines)


def main() -> None:
    if len(sys.argv) != 2 or sys.argv[1] not in ("--check", "--write"):
        sys.exit(f"usage: {sys.argv[0]} --check|--write")

    root_dirs = guarded_root_dirs()
    all_dirs = all_workspace_crate_dirs()
    closure_dirs = set(compute_closure(root_dirs))
    rendered = render_table(all_dirs, closure_dirs)

    if sys.argv[1] == "--write":
        TABLE_PATH.write_text(rendered)
        print(
            f"wrote {TABLE_PATH} ({len(closure_dirs)} of {len(all_dirs)} crates in the closure)",
        )
        return

    existing = TABLE_PATH.read_text() if TABLE_PATH.exists() else ""
    if existing != rendered:
        print(
            f"{TABLE_PATH} is stale: a dependency edge changed since it was last generated.\n"
            "Run `python3 scripts/ci/owner-chain-closure.py --write` and commit the result.",
            file=sys.stderr,
        )
        sys.exit(1)
    print(
        f"{TABLE_PATH} is current ({len(closure_dirs)} of {len(all_dirs)} crates in the closure)",
    )


if __name__ == "__main__":
    main()
