#!/usr/bin/env python3
"""
Compute, check, or regenerate the reverse-dependency table `plan.sh` scopes `rust-tests-linux-x86`
with: which packages' tests a change in one crate could possibly affect.

`owner-chain-closure.py` answers "does crate X reach an Owner root," a forward closure (X's own
dependencies). This answers the opposite direction: "which packages depend on crate X," a reverse
closure, because a change to X can only ever affect a consumer of X (or X itself), never the other
way. A dev dependency counts as a consumer too, the same bias `owner-chain-closure.py` already
documents: erring toward *more* packages in a crate's closure, never fewer, because `plan.sh`'s own
rule is "run the test when in doubt."

A crate with no entry, or one `cargo metadata` cannot resolve, is unscopeable: `plan.sh` treats
that the same way it treats every other thing it cannot classify - running every test, not a named
subset.

Usage:
    python3 rust-test-closure.py --check    # fails (and prints a diff) if the table is stale
    python3 rust-test-closure.py --write    # regenerates the table in place

"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
TABLE_PATH = REPO_ROOT / "scripts" / "ci" / "rust-test-crates.tsv"
TABLE_HEADER = (
    "# generated by scripts/ci/rust-test-closure.py --write; do not hand-edit.\n"
    "# <crate-dir>\\t<space-separated package names>: a change under <crate-dir> can only ever\n"
    "# affect these packages' tests - itself, plus every package that depends on it, directly or\n"
    "# transitively, including dev/build dependencies.\n"
)


def tool(name: str) -> str:
    """
    Resolve a required tool, or say that nothing here can be measured without it.
    """
    found = shutil.which(name)
    if found is None:
        sys.exit(f"ERROR: {name} is not on PATH, so the rust-test closure cannot be computed.")
    return found


def cargo_metadata(*extra_args: str) -> dict:
    """
    Run `cargo metadata` and parse its JSON.
    """
    raw = subprocess.run(
        [tool("cargo"), "metadata", "--format-version", "1", "--locked", *extra_args],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return json.loads(raw)


def crate_dir_of(pkg: dict, workspace_root: str) -> str:
    manifest = pkg["manifest_path"]
    prefix = workspace_root + "/"
    manifest = manifest.removeprefix(prefix)
    return manifest.rsplit("/", 1)[0]


def compute_reverse_closures() -> dict[str, list[str]]:
    """
    For every workspace crate directory, every package name whose tests a change there could
    affect: itself, plus every transitive dependent (normal, dev, or build).
    """
    metadata = cargo_metadata()
    members = set(metadata["workspace_members"])
    packages = {pkg["id"]: pkg for pkg in metadata["packages"] if pkg["id"] in members}
    workspace_root = metadata["workspace_root"]

    dir_of = {pkg_id: crate_dir_of(pkg, workspace_root) for pkg_id, pkg in packages.items()}
    name_of = {pkg_id: pkg["name"] for pkg_id, pkg in packages.items()}
    nodes = {node["id"]: node for node in metadata["resolve"]["nodes"] if node["id"] in members}

    # Reverse adjacency: dependents[B] holds every A with an edge A -> B.
    dependents: dict[str, set[str]] = {pkg_id: set() for pkg_id in packages}
    for pkg_id, node in nodes.items():
        for dep in node.get("deps", []):
            dep_id = dep.get("pkg")
            if dep_id in packages:
                dependents[dep_id].add(pkg_id)

    closures: dict[str, list[str]] = {}
    for pkg_id in packages:
        closure_ids = {pkg_id}
        stack = [pkg_id]
        while stack:
            current = stack.pop()
            for dependent_id in dependents.get(current, ()):
                if dependent_id not in closure_ids:
                    closure_ids.add(dependent_id)
                    stack.append(dependent_id)
        closures[dir_of[pkg_id]] = sorted(name_of[cid] for cid in closure_ids)

    return closures


def render_table(closures: dict[str, list[str]]) -> str:
    lines = [TABLE_HEADER]
    lines.extend(
        f"{crate_dir}\t{' '.join(names)}\n" for crate_dir, names in sorted(closures.items())
    )
    return "".join(lines)


def main() -> None:
    if len(sys.argv) != 2 or sys.argv[1] not in ("--check", "--write"):
        sys.exit(f"usage: {sys.argv[0]} --check|--write")

    closures = compute_reverse_closures()
    rendered = render_table(closures)

    if sys.argv[1] == "--write":
        TABLE_PATH.write_text(rendered)
        print(f"wrote {TABLE_PATH} ({len(closures)} crates)")
        return

    existing = TABLE_PATH.read_text() if TABLE_PATH.exists() else ""
    if existing != rendered:
        print(
            f"{TABLE_PATH} is stale: a dependency edge changed since it was last generated.\n"
            "Run `python3 scripts/ci/rust-test-closure.py --write` and commit the result.",
            file=sys.stderr,
        )
        sys.exit(1)
    print(f"{TABLE_PATH} is current ({len(closures)} crates)")


if __name__ == "__main__":
    main()
