use std::{fmt::Display, path::Path, sync::Arc};

use async_trait::async_trait;
use base64::{Engine as _, engine::general_purpose::STANDARD as BASE64};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use thiserror::Error;
use tokio::{
    io::{AsyncReadExt, AsyncWriteExt},
    net::UnixStream,
};

use crate::{
    artifact::{ArtifactIssuance, StrategyArtifact, StrategyArtifactIdentity, digest},
    cargo_artifact::{
        RUSTC_COMMIT, RUSTC_RELEASE, SANDBOX_POLICY_V1, SandboxedCargoBuildEvidence, TARGET,
        VerifiedCargoBuild,
    },
    product_edge::{
        FrozenResearchGoalIntentV1, ProductEdgeChannel, ResearchViewV1, TrustedProductEdgeContextV1,
    },
    program_runtime::ProgramRuntimeBudget,
};

pub const ARTIFACT_BUILD_OPERATION_V1: &str = "artifact_build.submit_or_resolve.v1";
pub const ARTIFACT_BUILD_SCHEMA_V1: &str = "rd-artifact-build-request-v1";
pub const ARTIFACT_BUILD_SCOPE_V1: &str = "research:artifact-build";
pub const ARTIFACT_VIEW_SCOPE_V1: &str = "research:view";
pub const SANDBOX_PROTOCOL_V1: &str = "rd-build-sandbox-v1";
pub const SANDBOX_SOCKET_DEFAULT: &str = "/run/trade-rd-sandbox/build.sock";
const MAX_WIRE_BYTES: usize = 12 * 1024 * 1024;
const MAX_EXPLANATION_BYTES: usize = 4_096;
const MAX_SUMMARY_BYTES: usize = 4_096;
pub(crate) const GENERATED_PROGRAM_MANIFEST: &str = r#"[package]
name = "rd-generated-strategy"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
publish = false

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[workspace]

[profile.release]
panic = "abort"
opt-level = "z"
codegen-units = 1
lto = "fat"
strip = "symbols"
"#;
pub(crate) const GENERATED_PROGRAM_LOCK: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "rd-generated-strategy"
version = "0.1.0"
"#;

#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ArtifactBuildRequestV1 {
    pub build_request_identity: String,
    pub attempt_identity: String,
    pub intent_identity: String,
    pub channel: ProductEdgeChannel,
    pub context: TrustedProductEdgeContextV1,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ArtifactBuildCandidateV1 {
    pub schema_version: u32,
    pub candidate_identity: String,
    pub intent_identity: String,
    pub intent_semantic_digest: String,
    pub logic: GeneratedStrategyLogicV1,
    pub structured_logic_summary: String,
    pub agent_change_explanation: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct GeneratedStrategyLogicV1 {
    pub signal: GeneratedSignalV1,
    pub direction: GeneratedDirectionV1,
    pub lookback_bars: u16,
    pub entry_threshold_bps: u16,
    pub exit_threshold_bps: u16,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum GeneratedSignalV1 {
    Momentum,
    MeanReversion,
    Breakout,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum GeneratedDirectionV1 {
    LongOnly,
    ShortOnly,
    LongShort,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ArtifactBuildPreparationV1 {
    pub schema_version: u32,
    pub resolution: ArtifactBuildResolution,
    pub build_request_identity: String,
    pub attempt_identity: String,
    pub semantic_digest: String,
    pub canonical_intent_bytes: Option<String>,
    pub intent_identity: Option<String>,
    pub intent_semantic_digest: Option<String>,
    pub owner_receipt: Option<ArtifactBuildReceiptV1>,
    pub next_legal_action: ArtifactBuildNextLegalAction,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ArtifactBuildResultV1 {
    pub schema_version: u32,
    pub resolution: ArtifactBuildResolution,
    pub build_request_identity: String,
    pub attempt_identity: String,
    pub owner_receipt: Option<ArtifactBuildReceiptV1>,
    pub research_view: Option<ResearchViewV1>,
    pub artifact_review: Option<ArtifactReviewV1>,
    pub next_legal_action: ArtifactBuildNextLegalAction,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ArtifactBuildResolution {
    Prepared,
    Success,
    FailedNoArtifact,
    RejectedNoWrite,
    OutcomeUnknown,
    SubmittedOrUnknown,
    IdentityConflict,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ArtifactBuildDisposition {
    Success,
    FailedNoArtifact,
    RejectedNoWrite,
    OutcomeUnknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ArtifactBuildNextLegalAction {
    RunBoundedExecutionAgent,
    ResolveSameAttemptIdentity,
    ReviewArtifact,
    CorrectInputAndCreateSuccessorRequest,
    CreateSuccessorBuildRequest,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ArtifactBuildReceiptV1 {
    pub schema_version: u32,
    pub receipt_identity: String,
    pub build_request_identity: String,
    pub attempt_identity: String,
    pub request_semantic_digest: String,
    pub intent_identity: Option<String>,
    pub intent_semantic_digest: Option<String>,
    pub disposition: ArtifactBuildDisposition,
    pub artifact_identity: Option<String>,
    pub build_receipt_identity: Option<String>,
    pub failure_code: Option<String>,
    pub committed_at_epoch_ms: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct BuildReceiptV1 {
    pub schema_version: u32,
    pub build_receipt_identity: String,
    pub attempt_identity: String,
    pub intent_identity: String,
    pub candidate_digest: String,
    pub source_capsule_digest: String,
    pub wasm_digest: String,
    pub build_recipe_digest: String,
    pub dependency_identity: String,
    pub rustc_release: String,
    pub rustc_commit: String,
    pub target: String,
    pub sandbox_policy: String,
    pub deterministic_double_build: bool,
    pub artifact_security_admission: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ArtifactReviewV1 {
    pub schema_version: u32,
    pub review_identity: String,
    pub artifact_identity: StrategyArtifactIdentity,
    pub intent_identity: String,
    pub intent_semantic_digest: String,
    pub request_identity: String,
    pub source_lineage: Vec<String>,
    pub structured_logic: GeneratedStrategyLogicV1,
    pub structured_logic_summary: String,
    pub parameters_identity: String,
    pub dependency_identity: String,
    pub build_receipt: BuildReceiptV1,
    pub build_security_state: String,
    pub agent_change_explanation: String,
    pub agent_change_explanation_authority: ExplanationAuthority,
    pub allowed_next_actions: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ExplanationAuthority {
    NonAuthoritativeAgentExplanation,
}

#[derive(Debug, Error)]
pub enum ArtifactBuildError {
    #[error("artifact build identity was reused with conflicting semantics")]
    ConflictingReplay,
    #[error("artifact build authorization lineage is not admitted: {0}")]
    Unauthorized(&'static str),
    #[error("artifact build candidate is invalid: {0}")]
    Candidate(&'static str),
    #[error("development sandbox unavailable: {0}")]
    Sandbox(String),
    #[error("R&D Owner storage unavailable: {0}")]
    Storage(String),
}

#[async_trait]
pub trait ArtifactBuildOwnerPort: Send + Sync {
    async fn prepare(
        &self,
        request: ArtifactBuildRequestV1,
    ) -> Result<ArtifactBuildPreparationV1, ArtifactBuildError>;

    async fn submit_candidate(
        &self,
        request: ArtifactBuildRequestV1,
        candidate: ArtifactBuildCandidateV1,
    ) -> Result<ArtifactBuildResultV1, ArtifactBuildError>;

    async fn fail_no_artifact(
        &self,
        request: ArtifactBuildRequestV1,
        failure_code: &str,
    ) -> Result<ArtifactBuildResultV1, ArtifactBuildError>;

    async fn resolve(
        &self,
        build_request_identity: &str,
        attempt_identity: &str,
        context: &TrustedProductEdgeContextV1,
    ) -> Result<ArtifactBuildResultV1, ArtifactBuildError>;
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SandboxBuildRequestV1 {
    pub protocol: String,
    pub candidate_digest: String,
    pub source: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct SandboxWireResponseV1 {
    protocol: String,
    outcome: String,
    failure_code: Option<String>,
    source_capsule_base64: Option<String>,
    build_recipe_base64: Option<String>,
    wasm_one_base64: Option<String>,
    wasm_two_base64: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct SandboxBuildProductV1 {
    pub(crate) source_capsule: Vec<u8>,
    pub(crate) build_recipe: Vec<u8>,
    pub(crate) wasm_one: Vec<u8>,
    pub(crate) wasm_two: Vec<u8>,
}

#[async_trait]
pub(crate) trait ArtifactBuildSandboxPort: Send + Sync {
    async fn build(
        &self,
        request: SandboxBuildRequestV1,
    ) -> Result<SandboxBuildProductV1, ArtifactBuildError>;
}

#[derive(Clone, Debug)]
pub(crate) struct UnixArtifactBuildSandboxV1 {
    socket: Arc<str>,
}

impl UnixArtifactBuildSandboxV1 {
    pub(crate) fn new(socket: impl Into<Arc<str>>) -> Self {
        Self {
            socket: socket.into(),
        }
    }
}

#[async_trait]
impl ArtifactBuildSandboxPort for UnixArtifactBuildSandboxV1 {
    async fn build(
        &self,
        request: SandboxBuildRequestV1,
    ) -> Result<SandboxBuildProductV1, ArtifactBuildError> {
        let request = serde_json::to_vec(&request).map_err(sandbox)?;
        if request.len() > MAX_WIRE_BYTES {
            return Err(ArtifactBuildError::Sandbox(
                "request exceeds bound".to_string(),
            ));
        }
        let mut stream = UnixStream::connect(Path::new(self.socket.as_ref()))
            .await
            .map_err(sandbox)?;
        stream
            .write_u32(u32::try_from(request.len()).map_err(sandbox)?)
            .await
            .map_err(sandbox)?;
        stream.write_all(&request).await.map_err(sandbox)?;
        stream.flush().await.map_err(sandbox)?;
        let length = usize::try_from(stream.read_u32().await.map_err(sandbox)?).map_err(sandbox)?;
        if length == 0 || length > MAX_WIRE_BYTES {
            return Err(ArtifactBuildError::Sandbox(
                "response exceeds bound".to_string(),
            ));
        }
        let mut bytes = vec![0; length];
        stream.read_exact(&mut bytes).await.map_err(sandbox)?;
        let response: SandboxWireResponseV1 = serde_json::from_slice(&bytes).map_err(sandbox)?;
        if response.protocol != SANDBOX_PROTOCOL_V1 || response.outcome != "SUCCESS" {
            return Err(ArtifactBuildError::Sandbox(
                response
                    .failure_code
                    .unwrap_or_else(|| "SANDBOX_REJECTED".to_string()),
            ));
        }
        Ok(SandboxBuildProductV1 {
            source_capsule: decode(response.source_capsule_base64, "source capsule")?,
            build_recipe: decode(response.build_recipe_base64, "build recipe")?,
            wasm_one: decode(response.wasm_one_base64, "first Wasm")?,
            wasm_two: decode(response.wasm_two_base64, "second Wasm")?,
        })
    }
}

pub(crate) fn success_wire_response(product: &SandboxBuildProductV1) -> Vec<u8> {
    serde_json::to_vec(&SandboxWireResponseV1 {
        protocol: SANDBOX_PROTOCOL_V1.to_string(),
        outcome: "SUCCESS".to_string(),
        failure_code: None,
        source_capsule_base64: Some(BASE64.encode(&product.source_capsule)),
        build_recipe_base64: Some(BASE64.encode(&product.build_recipe)),
        wasm_one_base64: Some(BASE64.encode(&product.wasm_one)),
        wasm_two_base64: Some(BASE64.encode(&product.wasm_two)),
    })
    .expect("sandbox response serialization is infallible")
}

pub(crate) fn failure_wire_response(code: &str) -> Vec<u8> {
    serde_json::to_vec(&SandboxWireResponseV1 {
        protocol: SANDBOX_PROTOCOL_V1.to_string(),
        outcome: "FAILED_NO_ARTIFACT".to_string(),
        failure_code: Some(code.to_string()),
        source_capsule_base64: None,
        build_recipe_base64: None,
        wasm_one_base64: None,
        wasm_two_base64: None,
    })
    .expect("sandbox response serialization is infallible")
}

pub(crate) fn decode_sandbox_request(
    bytes: &[u8],
) -> Result<SandboxBuildRequestV1, ArtifactBuildError> {
    if bytes.is_empty() || bytes.len() > MAX_WIRE_BYTES {
        return Err(ArtifactBuildError::Sandbox(
            "request exceeds bound".to_string(),
        ));
    }
    let request: SandboxBuildRequestV1 = serde_json::from_slice(bytes).map_err(sandbox)?;
    if request.protocol != SANDBOX_PROTOCOL_V1
        || request.source.is_empty()
        || request.source.len() > 128 * 1024
        || !valid_sha256(&request.candidate_digest)
    {
        return Err(ArtifactBuildError::Sandbox(
            "request is invalid".to_string(),
        ));
    }
    Ok(request)
}

pub(crate) fn verify_sandbox_product(
    product: &SandboxBuildProductV1,
    expected_source: &str,
) -> Result<VerifiedCargoBuild, ArtifactBuildError> {
    verify_sandbox_source_capsule(&product.source_capsule, expected_source.as_bytes())?;
    VerifiedCargoBuild::verify_sandboxed(SandboxedCargoBuildEvidence {
        wasm_one: &product.wasm_one,
        wasm_two: &product.wasm_two,
        source_capsule: &product.source_capsule,
        build_recipe: &product.build_recipe,
        runtime_budget: ProgramRuntimeBudget {
            max_module_bytes: 64 * 1024,
            fuel: 1_000_000,
        },
    })
    .map_err(|e| ArtifactBuildError::Sandbox(e.to_string()))
}

pub(crate) fn canonical_sandbox_source_capsule(
    source: &[u8],
) -> Result<Vec<u8>, ArtifactBuildError> {
    sandbox_source_capsule(
        GENERATED_PROGRAM_MANIFEST.as_bytes(),
        GENERATED_PROGRAM_LOCK.as_bytes(),
        source,
    )
}

fn verify_sandbox_source_capsule(
    actual: &[u8],
    expected_source: &[u8],
) -> Result<(), ArtifactBuildError> {
    let expected = canonical_sandbox_source_capsule(expected_source)?;
    if actual == expected {
        Ok(())
    } else {
        Err(ArtifactBuildError::Sandbox(
            "source capsule does not match the admitted candidate".to_string(),
        ))
    }
}

fn sandbox_source_capsule(
    manifest: &[u8],
    lock: &[u8],
    source: &[u8],
) -> Result<Vec<u8>, ArtifactBuildError> {
    let mut bytes = Vec::new();
    {
        let mut archive = tar::Builder::new(&mut bytes);
        append_capsule_entry(&mut archive, "Cargo.lock", lock)?;
        append_capsule_entry(&mut archive, "Cargo.toml", manifest)?;
        append_capsule_entry(&mut archive, "src/lib.rs", source)?;
        archive.finish().map_err(sandbox)?;
    }
    Ok(bytes)
}

fn append_capsule_entry(
    archive: &mut tar::Builder<&mut Vec<u8>>,
    path: &str,
    bytes: &[u8],
) -> Result<(), ArtifactBuildError> {
    let mut header = tar::Header::new_gnu();
    header.set_size(u64::try_from(bytes.len()).map_err(sandbox)?);
    header.set_mode(0o644);
    header.set_uid(0);
    header.set_gid(0);
    header.set_mtime(1);
    header.set_cksum();
    archive
        .append_data(&mut header, path, bytes)
        .map_err(sandbox)
}

pub(crate) fn validate_candidate(
    candidate: &ArtifactBuildCandidateV1,
    intent: &FrozenResearchGoalIntentV1,
) -> Result<String, ArtifactBuildError> {
    if candidate.schema_version != 1
        || candidate.intent_identity != intent.intent_identity
        || candidate.intent_semantic_digest != intent.semantic_digest
        || !candidate
            .candidate_identity
            .starts_with("agent-program-candidate-v1-")
        || !(16..=160).contains(&candidate.candidate_identity.len())
        || !candidate
            .candidate_identity
            .bytes()
            .all(valid_identity_byte)
    {
        return Err(ArtifactBuildError::Candidate("identity binding"));
    }

    if candidate.candidate_identity.contains("pilot")
        || candidate.candidate_identity.contains("template")
        || candidate
            .structured_logic_summary
            .contains("ResearchIntentProposal")
    {
        return Err(ArtifactBuildError::Candidate(
            "fixed or proposal-only candidate",
        ));
    }
    bounded_text(
        &candidate.structured_logic_summary,
        16,
        MAX_SUMMARY_BYTES,
        "logic summary",
    )?;
    bounded_text(
        &candidate.agent_change_explanation,
        16,
        MAX_EXPLANATION_BYTES,
        "agent explanation",
    )?;

    if !(2..=512).contains(&candidate.logic.lookback_bars)
        || !(1..=5_000).contains(&candidate.logic.entry_threshold_bps)
        || candidate.logic.exit_threshold_bps > candidate.logic.entry_threshold_bps
    {
        return Err(ArtifactBuildError::Candidate("logic parameters"));
    }
    candidate_digest(candidate)
}

pub(crate) fn candidate_digest(
    candidate: &ArtifactBuildCandidateV1,
) -> Result<String, ArtifactBuildError> {
    serde_json::to_vec(candidate)
        .map(|bytes| format!("sha256:{:x}", Sha256::digest(bytes)))
        .map_err(|_| ArtifactBuildError::Candidate("serialization"))
}

pub(crate) fn render_program_source(
    candidate: &ArtifactBuildCandidateV1,
    candidate_digest: &str,
) -> String {
    let tag = Sha256::digest(candidate_digest.as_bytes());
    let tag = tag.iter().map(u8::to_string).collect::<Vec<_>>().join(",");
    let signal = match candidate.logic.signal {
        GeneratedSignalV1::Momentum => 1,
        GeneratedSignalV1::MeanReversion => 2,
        GeneratedSignalV1::Breakout => 3,
    };
    let direction = match candidate.logic.direction {
        GeneratedDirectionV1::LongOnly => 1,
        GeneratedDirectionV1::ShortOnly => 2,
        GeneratedDirectionV1::LongShort => 3,
    };
    format!(
        r#"#![no_std]
use core::panic::PanicInfo;
const SIGNAL: u32 = {signal};
const DIRECTION: u32 = {direction};
const LOOKBACK: u32 = {lookback};
const ENTRY_BPS: u32 = {entry};
const EXIT_BPS: u32 = {exit};
const SEMANTIC_TAG: [u8; 32] = [{tag}];
static mut FRAME: [u8; 8192] = [0; 8192];
static mut OUTPUT: [u8; 8192] = [0; 8192];
#[unsafe(no_mangle)] pub extern "C" fn strategy_factory_frame_ptr_v1() -> u32 {{ core::ptr::addr_of_mut!(FRAME).cast::<u8>() as u32 }}
#[unsafe(no_mangle)] pub extern "C" fn strategy_factory_frame_capacity_v1() -> u32 {{ 8192 }}
#[unsafe(no_mangle)] pub extern "C" fn strategy_factory_proposal_ptr_v1() -> u32 {{ core::ptr::addr_of_mut!(OUTPUT).cast::<u8>() as u32 }}
#[unsafe(no_mangle)] pub extern "C" fn strategy_factory_proposal_capacity_v1() -> u32 {{ 8192 }}
#[unsafe(no_mangle)] pub extern "C" fn strategy_factory_on_event_v1(frame_len: u32) -> i32 {{
    if frame_len > 8192 {{ return -1; }}
    let index = ((frame_len ^ SIGNAL ^ DIRECTION ^ LOOKBACK ^ ENTRY_BPS ^ EXIT_BPS) & 31) as usize;
    unsafe {{ core::ptr::write_volatile(core::ptr::addr_of_mut!(OUTPUT).cast::<u8>(), SEMANTIC_TAG[index]); }}
    0
}}
#[panic_handler] fn panic(_: &PanicInfo<'_>) -> ! {{ loop {{ core::hint::spin_loop(); }} }}
"#,
        lookback = candidate.logic.lookback_bars,
        entry = candidate.logic.entry_threshold_bps,
        exit = candidate.logic.exit_threshold_bps,
    )
}

pub(crate) fn issue_artifact(
    intent_bytes: &[u8],
    attempt_identity: &str,
    candidate: &ArtifactBuildCandidateV1,
    build: &VerifiedCargoBuild,
) -> Result<StrategyArtifact, ArtifactBuildError> {
    let parameters = serde_json::to_vec(&candidate.logic)
        .map_err(|_| ArtifactBuildError::Candidate("logic serialization"))?;
    StrategyArtifact::issue(&ArtifactIssuance::program(
        2,
        intent_bytes,
        Some(digest(
            serde_json::to_vec(&candidate.logic)
                .map_err(|_| ArtifactBuildError::Candidate("logic serialization"))?
                .as_slice(),
        )),
        Some(attempt_identity.to_string()),
        Some(parameters),
        build,
    ))
    .map_err(|e| ArtifactBuildError::Storage(e.to_string()))
}

pub(crate) fn canonical_intent_bytes(
    intent: &FrozenResearchGoalIntentV1,
) -> Result<Vec<u8>, ArtifactBuildError> {
    let mut bytes =
        serde_json::to_vec(intent).map_err(|e| ArtifactBuildError::Storage(e.to_string()))?;
    bytes.push(b'\n');
    Ok(bytes)
}

pub(crate) fn build_request_semantic_digest(
    request: &ArtifactBuildRequestV1,
) -> Result<String, ArtifactBuildError> {
    #[derive(Serialize)]
    struct Meaning<'a> {
        build_request_identity: &'a str,
        attempt_identity: &'a str,
        intent_identity: &'a str,
        context: &'a TrustedProductEdgeContextV1,
    }

    for value in [
        request.build_request_identity.as_str(),
        request.attempt_identity.as_str(),
        request.intent_identity.as_str(),
    ] {
        if !(16..=160).contains(&value.len()) || !value.bytes().all(valid_identity_byte) {
            return Err(ArtifactBuildError::Candidate("request identity"));
        }
    }
    let bytes = serde_json::to_vec(&Meaning {
        build_request_identity: &request.build_request_identity,
        attempt_identity: &request.attempt_identity,
        intent_identity: &request.intent_identity,
        context: &request.context,
    })
    .map_err(|e| ArtifactBuildError::Storage(e.to_string()))?;
    Ok(format!("sha256:{:x}", Sha256::digest(bytes)))
}

pub(crate) fn build_receipt(
    attempt_identity: &str,
    intent_identity: &str,
    candidate_digest: &str,
    build: &VerifiedCargoBuild,
    artifact: &StrategyArtifact,
) -> BuildReceiptV1 {
    let identity = artifact.identity();
    BuildReceiptV1 {
        schema_version: 1,
        build_receipt_identity: format!(
            "rd-build-receipt-v1-{}",
            identity.artifact_digest.trim_start_matches("blake3:")
        ),
        attempt_identity: attempt_identity.to_string(),
        intent_identity: intent_identity.to_string(),
        candidate_digest: candidate_digest.to_string(),
        source_capsule_digest: identity.guest_source_digest.clone(),
        wasm_digest: identity.wasm_digest.clone(),
        build_recipe_digest: identity.build_recipe_digest.clone(),
        dependency_identity: "rust-core-only-locked-v1".to_string(),
        rustc_release: RUSTC_RELEASE.to_string(),
        rustc_commit: RUSTC_COMMIT.to_string(),
        target: TARGET.to_string(),
        sandbox_policy: SANDBOX_POLICY_V1.to_string(),
        deterministic_double_build: build.wasm.as_ref() == artifact.wasm(),
        artifact_security_admission: "ADMITTED".to_string(),
    }
}

pub(crate) fn artifact_review(
    intent: &FrozenResearchGoalIntentV1,
    candidate: &ArtifactBuildCandidateV1,
    artifact: &StrategyArtifact,
    receipt: BuildReceiptV1,
) -> ArtifactReviewV1 {
    let parameters = serde_json::to_vec(&candidate.logic).expect("typed logic serializes");
    ArtifactReviewV1 {
        schema_version: 1,
        review_identity: format!(
            "rd-artifact-review-v1-{}",
            artifact
                .identity()
                .artifact_digest
                .trim_start_matches("blake3:")
        ),
        artifact_identity: artifact.identity().clone(),
        intent_identity: intent.intent_identity.clone(),
        intent_semantic_digest: intent.semantic_digest.clone(),
        request_identity: intent.request_identity.clone(),
        source_lineage: intent
            .source_frontier
            .iter()
            .map(|source| format!("{}#{}", source.locator, source.content_digest))
            .collect(),
        structured_logic: candidate.logic.clone(),
        structured_logic_summary: candidate.structured_logic_summary.clone(),
        parameters_identity: digest(&parameters),
        dependency_identity: receipt.dependency_identity.clone(),
        build_receipt: receipt,
        build_security_state: "ADMITTED".to_string(),
        agent_change_explanation: candidate.agent_change_explanation.clone(),
        agent_change_explanation_authority: ExplanationAuthority::NonAuthoritativeAgentExplanation,
        allowed_next_actions: vec![
            "REVIEW_ARTIFACT".to_string(),
            "CREATE_SUCCESSOR_BUILD_REQUEST".to_string(),
        ],
    }
}

pub(crate) fn sandbox_request(
    candidate: &ArtifactBuildCandidateV1,
    digest: &str,
) -> SandboxBuildRequestV1 {
    SandboxBuildRequestV1 {
        protocol: SANDBOX_PROTOCOL_V1.to_string(),
        candidate_digest: digest.to_string(),
        source: render_program_source(candidate, digest),
    }
}

fn bounded_text(
    value: &str,
    minimum: usize,
    maximum: usize,
    label: &'static str,
) -> Result<(), ArtifactBuildError> {
    let trimmed = value.trim();
    if trimmed == value && (minimum..=maximum).contains(&value.len()) {
        Ok(())
    } else {
        Err(ArtifactBuildError::Candidate(label))
    }
}

fn valid_identity_byte(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b':' | b'.')
}

fn valid_sha256(value: &str) -> bool {
    value.strip_prefix("sha256:").is_some_and(|digest| {
        digest.len() == 64 && digest.bytes().all(|byte| byte.is_ascii_hexdigit())
    })
}

fn decode(value: Option<String>, label: &str) -> Result<Vec<u8>, ArtifactBuildError> {
    let value = value.ok_or_else(|| ArtifactBuildError::Sandbox(format!("missing {label}")))?;
    BASE64.decode(value).map_err(sandbox)
}

fn sandbox(error: impl Display) -> ArtifactBuildError {
    ArtifactBuildError::Sandbox(error.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::product_edge::{ResearchSourceV1, SourcedResearchGoalV1};
    use rstest::rstest;

    fn intent(identity: &str, digest: &str) -> FrozenResearchGoalIntentV1 {
        FrozenResearchGoalIntentV1 {
            schema_version: 1,
            intent_identity: identity.to_string(),
            request_identity: "research-request-01JZTEST0000000000000001".to_string(),
            semantic_digest: digest.to_string(),
            source_frontier: vec![ResearchSourceV1 {
                locator: "https://example.com/source".to_string(),
                content_digest: format!("sha256:{}", "a".repeat(64)),
                observed_at: "2026-08-18T12:00:00Z".to_string(),
                source_cut: "cut".to_string(),
                license_basis: "public".to_string(),
                interpretation: "bounded interpretation".to_string(),
            }],
            goal: SourcedResearchGoalV1 {
                hypothesis: "bounded momentum hypothesis".to_string(),
                mechanism: "bounded momentum mechanism".to_string(),
                falsification_question: "does the effect disappear after costs?".to_string(),
                expected_observation: "positive continuation".to_string(),
                required_data: vec!["PIT bars".to_string()],
                cost_assumption: "explicit fees".to_string(),
                capacity_assumption: "research only".to_string(),
                protected_feedback_frontier: "none".to_string(),
                sources: Vec::new(),
            },
            frozen_at_epoch_ms: 1,
        }
    }

    fn candidate(intent: &FrozenResearchGoalIntentV1) -> ArtifactBuildCandidateV1 {
        ArtifactBuildCandidateV1 {
            schema_version: 1,
            candidate_identity: "agent-program-candidate-v1-momentum-001".to_string(),
            intent_identity: intent.intent_identity.clone(),
            intent_semantic_digest: intent.semantic_digest.clone(),
            logic: GeneratedStrategyLogicV1 {
                signal: GeneratedSignalV1::Momentum,
                direction: GeneratedDirectionV1::LongOnly,
                lookback_bars: 24,
                entry_threshold_bps: 50,
                exit_threshold_bps: 10,
            },
            structured_logic_summary: "Use bounded 24-bar continuation with explicit thresholds."
                .to_string(),
            agent_change_explanation:
                "Generated a continuation candidate from the frozen mechanism.".to_string(),
        }
    }

    #[rstest]
    fn typed_candidate_is_bound_to_exact_owner_intent() {
        let frozen_intent = intent(
            "rd-research-intent-v1-exact",
            &format!("sha256:{}", "b".repeat(64)),
        );
        let candidate = candidate(&frozen_intent);
        assert!(validate_candidate(&candidate, &frozen_intent).is_ok());
        let foreign = intent(
            "rd-research-intent-v1-foreign",
            &format!("sha256:{}", "c".repeat(64)),
        );
        assert!(validate_candidate(&candidate, &foreign).is_err());
    }

    #[rstest]
    fn distinct_typed_logic_changes_rendered_program_source() {
        let intent = intent(
            "rd-research-intent-v1-exact",
            &format!("sha256:{}", "b".repeat(64)),
        );
        let first = candidate(&intent);
        let mut second = first.clone();
        second.logic.signal = GeneratedSignalV1::MeanReversion;
        second.logic.lookback_bars = 96;
        second.candidate_identity = "agent-program-candidate-v1-reversion-002".to_string();
        let first_digest = candidate_digest(&first).unwrap();
        let second_digest = candidate_digest(&second).unwrap();
        assert_ne!(first_digest, second_digest);
        assert_ne!(
            render_program_source(&first, &first_digest),
            render_program_source(&second, &second_digest)
        );
    }

    #[rstest]
    fn fixed_template_identity_is_rejected() {
        let intent = intent(
            "rd-research-intent-v1-exact",
            &format!("sha256:{}", "b".repeat(64)),
        );
        let mut candidate = candidate(&intent);
        candidate.candidate_identity = "agent-program-candidate-v1-pilot-template".to_string();
        assert!(validate_candidate(&candidate, &intent).is_err());
    }

    #[rstest]
    fn sandbox_capsule_is_bound_to_source_manifest_and_lock() {
        let source = b"canonical generated source";
        let canonical = canonical_sandbox_source_capsule(source).unwrap();
        assert!(verify_sandbox_source_capsule(&canonical, source).is_ok());

        for tampered in [
            sandbox_source_capsule(
                b"tampered manifest",
                GENERATED_PROGRAM_LOCK.as_bytes(),
                source,
            )
            .unwrap(),
            sandbox_source_capsule(
                GENERATED_PROGRAM_MANIFEST.as_bytes(),
                b"tampered lock",
                source,
            )
            .unwrap(),
            sandbox_source_capsule(
                GENERATED_PROGRAM_MANIFEST.as_bytes(),
                GENERATED_PROGRAM_LOCK.as_bytes(),
                b"tampered source",
            )
            .unwrap(),
        ] {
            assert!(verify_sandbox_source_capsule(&tampered, source).is_err());
        }

        let mut tampered = canonical;
        tampered[0] ^= 1;
        assert!(verify_sandbox_source_capsule(&tampered, source).is_err());
    }
}
