//! Compatibility facade for the R&D-owned canonical Replay runner profile.

pub use vibe_rd_exploratory_replay_custody::replay_runner_operational_profile_v1::*;

#[cfg(test)]
pub(crate) fn runner_fixture() -> ReplayRunnerOperationalProfileInputV1 {
    ReplayRunnerOperationalProfileInputV1 {
        schema_version: 1,
        environment: ReplayRunnerEnvironmentV1::Backtest,
        trader_identity: "BACKTESTER-001".into(),
        load_state: false,
        save_state: false,
        shutdown_on_error: true,
        logging: ReplayRunnerLoggerConfigV1 {
            stdout_level: ReplayRunnerLogLevelV1::Off,
            fileout_level: ReplayRunnerLogLevelV1::Off,
            component_level: Vec::new(),
            module_level: Vec::new(),
            log_components_only: false,
            is_colored: false,
            print_config: false,
            use_tracing: false,
            bypass_logging: true,
            file_config: ReplayRunnerFileLoggingV1::Disabled,
            clear_log_file: false,
            fileout_sync_on_flush: false,
            buffered_stdout: false,
        },
        instance_identity: ReplayRunnerInstanceIdentityV1::DeterministicFromRequest,
        timeout_connection_ns: 60_000_000_000,
        timeout_reconciliation_ns: 30_000_000_000,
        timeout_portfolio_ns: 10_000_000_000,
        timeout_disconnection_ns: 10_000_000_000,
        delay_post_stop_ns: 10_000_000_000,
        timeout_shutdown_ns: 5_000_000_000,
        cache: ReplayRunnerCacheConfigV1 {
            encoding: ReplayRunnerSerializationEncodingV1::Json,
            timestamps_as_iso8601: false,
            buffer_interval_ms: None,
            bulk_read_batch_size: None,
            use_trader_prefix: true,
            use_instance_id: true,
            flush_on_start: true,
            drop_instruments_on_reset: false,
            tick_capacity: 10_000,
            bar_capacity: 10_000,
            persist_account_events: false,
            save_market_data: false,
        },
        message_bus: ReplayRunnerMessageBusConfigV1 {
            encoding: ReplayRunnerSerializationEncodingV1::Json,
            encoding_market_data: None,
            encoding_builtin: None,
            timestamps_as_iso8601: false,
            buffer_interval_ms: None,
            autotrim_mins: None,
            autotrim_maxlen: None,
            use_trader_prefix: true,
            use_trader_id: true,
            use_instance_id: true,
            streams_prefix: "stream".into(),
            stream_per_topic: true,
            external_streams: None,
            types_filter: None,
            heartbeat_interval_secs: None,
        },
        data_engine: ReplayRunnerDataEngineConfigV1 {
            time_bars_build_with_no_updates: false,
            time_bars_timestamp_on_close: true,
            time_bars_skip_first_non_full_bar: false,
            time_bars_interval_type: ReplayRunnerBarIntervalTypeV1::LeftOpen,
            time_bars_build_delay: 0,
            time_bars_origin_offset: Vec::new(),
            validate_data_sequence: true,
            buffer_deltas: false,
            emit_quotes_from_book: false,
            emit_quotes_from_book_depths: false,
            disable_historical_cache: true,
            external_clients: None,
            debug: false,
        },
        risk_engine: ReplayRunnerRiskEngineConfigV1 {
            bypass: false,
            max_order_submit: ReplayRunnerRateLimitV1 {
                limit: 100,
                interval_ns: 1_000_000_000,
            },
            max_order_modify: ReplayRunnerRateLimitV1 {
                limit: 100,
                interval_ns: 1_000_000_000,
            },
            max_notional_per_order: Vec::new(),
            debug: false,
        },
        execution_engine: ReplayRunnerExecutionEngineConfigV1 {
            load_cache: false,
            manage_own_order_books: false,
            snapshot_orders: false,
            snapshot_positions: false,
            snapshot_positions_interval: ReplayRunnerFloatOnlyIntervalV1::Disabled,
            carry_replay_events_on_reopen: false,
            allow_overfills: false,
            filter_unclaimed_external_orders: false,
            external_clients: None,
            purge_closed_orders_interval_mins: None,
            purge_closed_orders_buffer_mins: None,
            purge_closed_positions_interval_mins: None,
            purge_closed_positions_buffer_mins: None,
            purge_account_events_interval_mins: None,
            purge_account_events_lookback_mins: None,
            purge_from_database: false,
            debug: false,
        },
        portfolio: ReplayRunnerPortfolioConfigV1 {
            use_mark_prices: true,
            use_mark_xrates: false,
            bar_updates: false,
            convert_to_account_base_currency: true,
            equity_curve: true,
            min_account_state_logging_interval_ms: None,
            snapshot_interval_ms: None,
            debug: false,
        },
        controller: ReplayRunnerOptionalSubsystemV1::Disabled,
        streaming: ReplayRunnerOptionalSubsystemV1::Disabled,
        bypass_logging: true,
        run_analysis: false,
    }
}
