import {
  Activity,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  Archive,
  Ban,
  BarChart3,
  Bell,
  Boxes,
  CalendarDays,
  CalendarRange,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDashed,
  CircleHelp,
  Clock3,
  Clipboard,
  Columns3,
  Cpu,
  Database,
  Download,
  ExternalLink,
  FileCheck2,
  FileSearch2,
  FlaskConical,
  Gem,
  GitBranch,
  Grid2X2,
  Grid3X3,
  Hash,
  History,
  LayoutGrid,
  LineChart,
  List,
  ListFilter,
  LockKeyhole,
  Loader2,
  Menu,
  Moon,
  PackageOpen,
  PackageCheck,
  Play,
  Plus,
  Radio,
  ReceiptText,
  RefreshCw,
  RotateCcw,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Sun,
  TerminalSquare,
  Table2,
  TimerReset,
  TriangleAlert,
  Trash2,
  Users,
  Wallet,
  Workflow,
  X,
  XCircle,
  type LucideIcon,
} from "lucide-react";

// UI icons are selected from the pinned Lucide collection and exposed through
// semantic names. Pages never draw or source their own interface glyphs.
export type DashboardIcon = LucideIcon;

export const InterfaceIcons = {
  menu: Menu,
  search: Search,
  notification: Bell,
  themeDark: Moon,
  themeLight: Sun,
  refresh: RefreshCw,
  copy: Clipboard,
  download: Download,
  filter: ListFilter,
  selected: Check,
  expand: ChevronDown,
  previous: ChevronLeft,
  next: ChevronRight,
  sortAscending: ArrowUp,
  sortDescending: ArrowDown,
  delete: Trash2,
  open: ExternalLink,
  autoRefresh: TimerReset,
  calendar: CalendarDays,
  calendarAgenda: CalendarRange,
  calendarDay: List,
  calendarWeek: Columns3,
  calendarMonth: Grid3X3,
  calendarYear: Grid2X2,
  table: Table2,
  settings: Settings,
  list: List,
  close: X,
} satisfies Record<string, DashboardIcon>;

export const ModuleIcons = {
  activity: LineChart,
  blocks: Workflow,
  briefcase: Wallet,
  chart: BarChart3,
  cpu: Cpu,
  database: Database,
  flask: FlaskConical,
  layout: LayoutGrid,
  scan: Gem,
  settings: Settings,
  shield: ShieldCheck,
  terminal: TerminalSquare,
  triangle: Shield,
} satisfies Record<string, DashboardIcon>;

export const RunIcons = {
  all: ListFilter,
  queued: Clock3,
  running: Loader2,
  succeeded: CheckCircle2,
  failed: XCircle,
  cancelled: Ban,
  unknown: CircleHelp,
  loaded: Database,
  run: Hash,
  operation: Workflow,
  kind: Boxes,
  state: Activity,
  duration: Clock3,
  created: CalendarClock,
  archive: Archive,
  dependency: PackageOpen,
  consumer: Users,
  history: History,
  protected: ShieldAlert,
} satisfies Record<string, DashboardIcon>;

export const EvidenceIcons = {
  next: ArrowRight,
  pending: CircleDashed,
  artifact: FileCheck2,
  inspectFile: FileSearch2,
  research: FlaskConical,
  branch: GitBranch,
  locked: LockKeyhole,
  packageVerified: PackageCheck,
  run: Play,
  add: Plus,
  live: Radio,
  receipt: ReceiptText,
  replay: RotateCcw,
  magic: Sparkles,
  verified: ShieldCheck,
  warning: TriangleAlert,
} satisfies Record<string, DashboardIcon>;
