from __future__ import annotations

import ast
import importlib
from pathlib import Path

import pytest


PYTHON_ROOT = Path(__file__).resolve().parents[2]
PACKAGE_ROOT = PYTHON_ROOT / "vibe_trader"
GENERATED_HEADER = "# This file is automatically generated by pyo3_stub_gen"


def _generated_module_classes() -> list[tuple[str, tuple[str, ...]]]:
    parameters = []

    for stub_path in sorted(PACKAGE_ROOT.rglob("__init__.pyi")):
        source = stub_path.read_text()
        if not source.startswith(GENERATED_HEADER):
            continue

        module_name = ".".join(stub_path.parent.relative_to(PYTHON_ROOT).parts)
        class_names = tuple(
            node.name for node in ast.parse(source).body if isinstance(node, ast.ClassDef)
        )

        if class_names:
            parameters.append((module_name, class_names))

    return parameters


GENERATED_MODULE_CLASSES = _generated_module_classes()


def test_generated_public_modules_discovered() -> None:
    assert GENERATED_MODULE_CLASSES, "No generated public modules discovered"


@pytest.mark.parametrize(
    ("module_name", "class_names"),
    GENERATED_MODULE_CLASSES,
    ids=[module_name for module_name, _ in GENERATED_MODULE_CLASSES],
)
def test_generated_classes_use_public_module(
    module_name: str,
    class_names: tuple[str, ...],
) -> None:
    module = importlib.import_module(module_name)
    missing = []
    non_types = []
    misowned = []

    for name in class_names:
        obj = getattr(module, name, None)
        if obj is None:
            missing.append(name)
        elif not isinstance(obj, type):
            non_types.append(name)
        elif obj.__module__ != module_name:
            misowned.append(f"{name} -> {obj.__module__}")

    assert not missing, f"{module_name} generated classes missing at runtime: {missing}"
    assert not non_types, f"{module_name} generated classes are not types: {non_types}"
    assert not misowned, f"{module_name} generated classes have wrong owners: {misowned}"
