import { expect, test } from "bun:test"
import { CONTROL_PLANE_IDENTITY_SCHEMA_VERSION } from "../../../../research-control-plane/contracts/src/lib/control-plane-contracts"
import { REPLAY_DECISION_INPUT_SNAPSHOT_SCHEMA_VERSION, REPLAY_EQUITY_POLICY_VERSION, REPLAY_JOURNAL_POLICY_VERSION, REPLAY_MARGIN_POLICY_VERSION, REPLAY_NUMERIC_POLICY_VERSION, REPLAY_RESULT_SCHEMA_VERSION, type ReplayResult } from "../../../../replay-execution-plane/contracts/src/lib/replay-contracts"
import { buildDraftAuthorization } from "./reviewer-role"

const HASH = "1".repeat(64)
const identity = { schema_version: CONTROL_PLANE_IDENTITY_SCHEMA_VERSION, experiment_id: "experiment-1", trial_group_id: "group-1", trial_group_hash: HASH, trial_id: "trial-1", candidate_id: "candidate-1", candidate_hash: HASH, identity_hash_policy_version: "identity-v1", experiment_contract_hash: HASH }
const result: ReplayResult = {
  schema_version: REPLAY_RESULT_SCHEMA_VERSION, run_id: "run-1", status: "completed", started_at: "2026-07-14T04:00:00Z", completed_at: "2026-07-14T08:00:00Z", source_events: [], order_events: [], fills: [], positions: [], ledger: [], journal: [],
  valuation_snapshot: { valuation_id: "valuation-1", event_key: { event_time: "2026-07-14T08:00:00Z", boundary_phase: 100, source_sequence: 1, event_subphase: 0, stable_event_id: "valuation" }, timestamp: "2026-07-14T08:00:00Z", position_event_id: "position-1", mark_source_ref: "fill-2", mark_source: "fill_price", symbol: "BTCUSDT", settlement_asset: "USDT", mark_price: 110, signed_quantity: 0, average_entry_price: null, unrealized_pnl: 0 },
  equity_bridge: { policy_version: REPLAY_EQUITY_POLICY_VERSION, valuation_id: "valuation-1", settlement_asset: "USDT", terminal_position_state: "flat", cash_balance: 1010, position_valuation: 0, ending_equity: 1010, reconciled: true },
  margin_snapshots: [{ policy_version: REPLAY_MARGIN_POLICY_VERSION, venue_risk_policy_snapshot_id: "risk-1", venue_risk_policy_snapshot_hash: HASH, snapshot_id: "margin-terminal", snapshot_sequence: 1, stage: "terminal", event_key: { event_time: "2026-07-14T08:00:00Z", boundary_phase: 100, source_sequence: 1, event_subphase: 0, stable_event_id: "margin" }, timestamp: "2026-07-14T08:00:00Z", position_event_id: "position-1", mark_source_ref: "fill-2", mark_source: "fill_price", resolution: "not_applicable_flat", symbol: "BTCUSDT", collateral_asset: "USDT", signed_quantity: 0, mark_price: 110, notional: 0, isolated_collateral: 0, attributed_settled_cashflow: 0, unrealized_pnl: 0, margin_balance: 0, initial_margin_requirement: 0, maintenance_margin_requirement: 0, initial_margin_headroom: 0, maintenance_margin_headroom: 0, margin_ratio: null, initial_margin_sufficient: true, maintenance_margin_sufficient: true, maintenance_trigger: "margin_balance_below_maintenance_requirement", maintenance_breach_observed: false, breach_terminal_priority: "risk_before_strategy_exit", state: "flat", liquidation_evaluated: false }], liquidation: null,
  trial_balance: { policy_version: REPLAY_JOURNAL_POLICY_VERSION, settlement_asset: "USDT", debit_total: 0, credit_total: 0, account_balances: [], wallet_cash_balance: 1010, isolated_margin_collateral_balance: 0, settled_cash_balance: 1010, position_valuation_balance: 0, ending_equity: 1010, balanced: true },
  supplemental_evidence: { visibility_policy: "signal_time_snapshot", requirement_set_hash: "f126b641e1c2e55c174e3505e15232b466e50c3fd764f30968a925821c31d144", undeclared_input_policy: "reject", decision_time: "2026-07-14T04:00:00Z", supplied_record_count: 0, selected_record_ids: [], selected_records_hash: "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945", future_revision_count: 0, requirement_evaluations: [], decision_input_snapshot_hash: HASH },
  decision_harness_bundle: null,
  decision_input_snapshot: { schema_version: REPLAY_DECISION_INPUT_SNAPSHOT_SCHEMA_VERSION, run_id: "run-1", decision_time: "2026-07-14T04:00:00Z", supplemental_requirement_set_hash: "f126b641e1c2e55c174e3505e15232b466e50c3fd764f30968a925821c31d144", visibility_policy: "signal_time_snapshot", selected_records: [], selected_records_hash: "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945", snapshot_hash: HASH },
  decision_harness_receipt: null,
  metrics: { initial_cash: 1000, ending_equity: 1010, net_pnl: 10, return_fraction: 0.01, realized_pnl: 10, unrealized_pnl: 0, total_fees: 0, total_liquidation_fees: 0, total_funding: 0, trade_count: 1, margin_observation_count: 1, peak_observed_margin_ratio: null, terminal_margin_ratio: null, observed_maintenance_breach_count: 0 }, limitations: [],
  fingerprint: { experiment_contract_hash: HASH, trial_group_hash: HASH, candidate_hash: HASH, identity_hash_policy_version: "identity-v1", trial_reservation_hash: HASH, dataset_manifest_hash: HASH, dataset_hash: HASH, supplemental_facts_hash: "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945", supplemental_requirement_set_hash: "f126b641e1c2e55c174e3505e15232b466e50c3fd764f30968a925821c31d144", decision_input_snapshot_hash: HASH, decision_harness_receipt_hash: null, decision_harness_bundle_hash: null, decision_harness_registry_policy_version: null, decision_harness_loader_policy_version: null, venue_risk_policy_schedule_hash: HASH, instrument_spec_schedule_hash: HASH, harness_hash: HASH, assumptions_hash: HASH, cost_policy_hash: HASH, simulator_policy_version: "sim-v1", numeric_policy_version: REPLAY_NUMERIC_POLICY_VERSION, journal_policy_version: REPLAY_JOURNAL_POLICY_VERSION, equity_policy_version: REPLAY_EQUITY_POLICY_VERSION, margin_policy_version: REPLAY_MARGIN_POLICY_VERSION, margin_policy_hash: HASH, request_hash: HASH, result_hash: HASH, random_seed: 1 },
}

test("Reviewer produces authorization but does not write strategy or lifecycle", () => {
  const authorization = buildDraftAuthorization({ decision_id: "decision-1", reviewer_run_id: "review-1", primary_result_id: "result-1", selected_trial_id: "trial-1", selected_candidate_id: "candidate-1", candidate_frozen_at: "2026-07-14T08:00:00Z", explicit_decision: "accept_for_draft", identity, result })
  expect(authorization.decision).toBe("accept_for_draft")
  expect(authorization.primary_result_hash).toBe(HASH)
})
