#!/usr/bin/env bun

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs"
import { dirname, join, normalize } from "node:path"
import ts from "typescript"

type JSONRecord = Record<string, unknown>

interface DomainRecord {
  id: string
  modules: string[]
}

interface JobRecord {
  ticketNo: string
  jobId: string
  targetDomain: string
  ownerModule: string
  writes: string[]
}

interface StoreRecord {
  id: string
  ownerDomain: string
  ownerModule: string
}

interface ImportEdge {
  file: string
  sourceModule: string
  sourceDomain: string
  targetModule: string
  targetDomain: string
  specifier: string
}

const args = new Set(process.argv.slice(2))
const writeMode = args.has("--write")
const checkMode = args.has("--check")

const manifest = readJson("docs/architecture-manifest.json")
const domains = arrayOfRecords(manifest.domains).map((domain): DomainRecord => ({
  id: stringField(domain.id),
  modules: stringArray(domain.modules),
}))
const jobs = arrayOfRecords(manifest.jobs).map((job): JobRecord => ({
  ticketNo: stringField(job.ticket_no),
  jobId: stringField(job.job_id),
  targetDomain: stringField(job.target_domain),
  ownerModule: stringField(job.owner_module),
  writes: stringArray(job.writes),
}))
const stores = arrayOfRecords(manifest.stores).map((store): StoreRecord => ({
  id: stringField(store.id),
  ownerDomain: stringField(store.owner_domain),
  ownerModule: stringField(store.owner_module),
}))

const moduleToDomain = new Map<string, string>()
for (const domain of domains) {
  for (const modulePath of domain.modules) {
    moduleToDomain.set(normalizePath(modulePath), domain.id)
  }
}

const packageModules = findMarkerRoots("modules", "package.json")
const executablePackageModules = packageModules.filter((path) => !path.startsWith("modules/contracts/"))
const orphanPackageModules = executablePackageModules.filter((path) => !moduleToDomain.has(path))
const missingManifestModules = [...moduleToDomain.keys()].filter((path) => !existsSync(path))
const contractRoots = findMarkerRoots("modules", "CONTRACT.md")
const contractRootsOutsideManifest = contractRoots
  .filter((path) => !path.startsWith("modules/contracts/"))
  .filter((path) => !moduleToDomain.has(path))

const importEdges = readTsImportEdges()
const crossDomainImportEdges = importEdges
  .filter((edge) => edge.sourceDomain && edge.targetDomain && edge.sourceDomain !== edge.targetDomain)
  .filter((edge) => edge.targetDomain !== "contracts")

const jobOwnerMismatches = jobs.filter((job) => {
  const ownerDomain = ownerDomainForModule(job.ownerModule)
  return ownerDomain && ownerDomain !== job.targetDomain
})

const hardIssues = [
  ...orphanPackageModules.map((path) => `package module is not declared in architecture manifest: ${path}`),
  ...missingManifestModules.map((path) => `architecture manifest module path does not exist: ${path}`),
]

const report = buildReport()
const mermaid = buildMermaid()
const reportPath = "docs/generated/architecture-drift-report.md"
const mermaidPath = "docs/generated/code-architecture-current.mmd"

if (writeMode) {
  mkdirSync(dirname(reportPath), { recursive: true })
  writeFileSync(reportPath, report)
  writeFileSync(mermaidPath, mermaid)
}

if (checkMode) {
  if (!existsSync(reportPath) || readFileSync(reportPath, "utf8") !== report) {
    hardIssues.push(`generated report is stale; run: bun scripts/architecture-drift-audit.ts --write`)
  }
  if (!existsSync(mermaidPath) || readFileSync(mermaidPath, "utf8") !== mermaid) {
    hardIssues.push(`generated mermaid is stale; run: bun scripts/architecture-drift-audit.ts --write`)
  }
}

if (hardIssues.length > 0) {
  console.error(`architecture drift audit failed:\n${hardIssues.join("\n")}`)
  process.exit(1)
}

if (!writeMode && !checkMode) {
  process.stdout.write(report)
}

function buildReport(): string {
  const lines: string[] = []
  lines.push("# Architecture Drift Report")
  lines.push("")
  lines.push("> Generated by `bun scripts/architecture-drift-audit.ts --write`. Do not edit by hand.")
  lines.push("")
  lines.push("## Verdict")
  lines.push("")
  if (orphanPackageModules.length === 0 && missingManifestModules.length === 0) {
    lines.push("- Hard drift: none.")
  } else {
    for (const issue of hardIssues) {
      lines.push(`- Hard drift: ${issue}`)
    }
  }
  lines.push(`- Cross-domain source imports visible from code: ${crossDomainImportEdges.length}. These are implementation projection lines, not protocol rails.`)
  lines.push("- Test files are excluded from the flyline count.")
  lines.push(`- Job owner / target-domain mismatches visible from manifest: ${jobOwnerMismatches.length}.`)
  lines.push(`- CONTRACT roots outside manifest domain module list: ${contractRootsOutsideManifest.length}. These are usually internal engines or pending module declarations.`)
  lines.push("")
  lines.push("## Domain Projection")
  lines.push("")
  lines.push("| Domain | Manifest modules | Package-backed modules | Owns stores | Owns jobs |")
  lines.push("| --- | ---: | ---: | --- | --- |")
  for (const domain of domains) {
    const packageCount = domain.modules.filter((modulePath) => packageModules.includes(modulePath)).length
    const ownedStores = stores.filter((store) => store.ownerDomain === domain.id).map((store) => store.id).join(", ") || "-"
    const ownedJobs = jobs.filter((job) => job.targetDomain === domain.id).map((job) => `${job.ticketNo}:${job.jobId}`).join(", ") || "-"
    lines.push(`| \`${domain.id}\` | ${domain.modules.length} | ${packageCount} | ${ownedStores} | ${ownedJobs} |`)
  }
  lines.push("")
  lines.push("## Job Ownership")
  lines.push("")
  lines.push("| Ticket | Job | Target domain | Owner module | Owner module domain | Writes |")
  lines.push("| --- | --- | --- | --- | --- | --- |")
  for (const job of jobs) {
    const ownerDomain = ownerDomainForModule(job.ownerModule) || "unknown"
    lines.push(`| \`${job.ticketNo}\` | \`${job.jobId}\` | \`${job.targetDomain}\` | \`${job.ownerModule}\` | \`${ownerDomain}\` | ${job.writes.map((write) => `\`${write}\``).join(", ") || "-"} |`)
  }
  lines.push("")
  lines.push("## Code Flylines")
  lines.push("")
  if (crossDomainImportEdges.length === 0) {
    lines.push("- None.")
  } else {
    lines.push("| Source domain | Target domain | Source module | Target module | Files |")
    lines.push("| --- | --- | --- | --- | ---: |")
    for (const item of aggregateImportEdges(crossDomainImportEdges)) {
      lines.push(`| \`${item.sourceDomain}\` | \`${item.targetDomain}\` | \`${item.sourceModule}\` | \`${item.targetModule}\` | ${item.files.length} |`)
    }
  }
  lines.push("")
  lines.push("## Orphan Package Modules")
  lines.push("")
  if (orphanPackageModules.length === 0) {
    lines.push("- None.")
  } else {
    for (const path of orphanPackageModules) {
      lines.push(`- \`${path}\``)
    }
  }
  lines.push("")
  lines.push("## Contract Roots Outside Manifest")
  lines.push("")
  if (contractRootsOutsideManifest.length === 0) {
    lines.push("- None.")
  } else {
    for (const path of contractRootsOutsideManifest) {
      lines.push(`- \`${path}\``)
    }
  }
  lines.push("")
  lines.push("## Generated Mermaid")
  lines.push("")
  lines.push("- Current implementation projection: [code-architecture-current.mmd](code-architecture-current.mmd)")
  lines.push("- Blueprint source of truth: [../architecture-overview-v2.mmd](../architecture-overview-v2.mmd)")
  lines.push("")
  return `${lines.join("\n")}\n`
}

function buildMermaid(): string {
  const lines: string[] = []
  lines.push("flowchart LR")
  lines.push("  blueprint[\"Blueprint: architecture-overview-v2.mmd\"]")
  lines.push("  generated[\"Generated from code + manifest\"]")
  lines.push("  blueprint -. compare .- generated")
  for (const domain of domains) {
    const domainNode = domainId(domain.id)
    lines.push(`  subgraph ${domainNode}["${escapeLabel(domain.id)}"]`)
    for (const modulePath of domain.modules) {
      const moduleNode = moduleId(modulePath)
      lines.push(`    ${moduleNode}["${escapeLabel(stripModulesPrefix(modulePath))}"]`)
    }
    lines.push("  end")
  }
  for (const job of jobs) {
    const ownerNode = moduleId(job.ownerModule)
    const targetNode = domainId(job.targetDomain)
    lines.push(`  generated -- "${escapeLabel(`${job.ticketNo} ${job.jobId}`)}" --> ${targetNode}`)
    if (moduleToDomain.has(normalizePath(job.ownerModule))) {
      lines.push(`  ${ownerNode} -. "owner" .-> ${targetNode}`)
    }
  }
  for (const store of stores) {
    const storeNode = `store_${safeId(store.id)}`
    lines.push(`  ${storeNode}[("${escapeLabel(store.id)}")]`)
    lines.push(`  ${domainId(store.ownerDomain)} -- "owns store" --> ${storeNode}`)
  }
  for (const item of aggregateImportEdges(crossDomainImportEdges)) {
    lines.push(`  ${moduleId(item.sourceModule)} -. "${item.files.length} import" .-> ${moduleId(item.targetModule)}`)
  }
  return `${lines.join("\n")}\n`
}

function aggregateImportEdges(edges: ImportEdge[]): Array<{
  sourceDomain: string
  targetDomain: string
  sourceModule: string
  targetModule: string
  files: string[]
}> {
  const groups = new Map<string, {
    sourceDomain: string
    targetDomain: string
    sourceModule: string
    targetModule: string
    files: Set<string>
  }>()
  for (const edge of edges) {
    const key = `${edge.sourceModule} -> ${edge.targetModule}`
    const existing = groups.get(key)
    if (existing) {
      existing.files.add(edge.file)
    } else {
      groups.set(key, {
        sourceDomain: edge.sourceDomain,
        targetDomain: edge.targetDomain,
        sourceModule: edge.sourceModule,
        targetModule: edge.targetModule,
        files: new Set([edge.file]),
      })
    }
  }
  return [...groups.values()]
    .map((item) => ({ ...item, files: [...item.files].sort() }))
    .sort((a, b) => `${a.sourceDomain}/${a.sourceModule}/${a.targetModule}`.localeCompare(`${b.sourceDomain}/${b.sourceModule}/${b.targetModule}`))
}

function readTsImportEdges(): ImportEdge[] {
  const edges: ImportEdge[] = []
  const tsFiles = walkFiles("modules").filter((file) => file.endsWith(".ts") && !file.endsWith(".test.ts"))
  for (const file of tsFiles) {
    const sourceModule = ownerModuleForPath(file)
    if (!sourceModule) continue
    const sourceDomain = ownerDomainForModule(sourceModule)
    const sourceFile = ts.createSourceFile(file, readFileSync(file, "utf8"), ts.ScriptTarget.ESNext, true, ts.ScriptKind.TS)
    visitImports(sourceFile, (specifier) => {
      if (!specifier.startsWith(".")) return
      const resolved = normalizePath(normalize(join(dirname(file), specifier)))
      const targetModule = ownerModuleForPath(resolved)
      if (!targetModule || targetModule === sourceModule) return
      const targetDomain = ownerDomainForModule(targetModule)
      edges.push({
        file,
        sourceModule,
        sourceDomain,
        targetModule,
        targetDomain,
        specifier,
      })
    })
  }
  return edges.sort((a, b) => `${a.file}:${a.specifier}`.localeCompare(`${b.file}:${b.specifier}`))
}

function visitImports(node: ts.Node, onSpecifier: (specifier: string) => void): void {
  if ((ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) && node.moduleSpecifier && ts.isStringLiteral(node.moduleSpecifier)) {
    onSpecifier(node.moduleSpecifier.text)
  }
  if (ts.isCallExpression(node) && node.expression.kind === ts.SyntaxKind.ImportKeyword) {
    const [arg] = node.arguments
    if (arg && ts.isStringLiteral(arg)) {
      onSpecifier(arg.text)
    }
  }
  ts.forEachChild(node, (child) => visitImports(child, onSpecifier))
}

function ownerModuleForPath(path: string): string {
  const normalized = normalizePath(path)
  const moduleRoots = [
    ...moduleToDomain.keys(),
    ...packageModules.filter((modulePath) => modulePath.startsWith("modules/contracts/")),
  ].sort((a, b) => b.length - a.length)
  return moduleRoots.find((root) => normalized === root || normalized.startsWith(`${root}/`)) || ""
}

function ownerDomainForModule(modulePath: string): string {
  const normalized = normalizePath(modulePath)
  if (normalized.startsWith("modules/contracts/")) {
    return "contracts"
  }
  return moduleToDomain.get(normalized) || ""
}

function findMarkerRoots(dir: string, marker: string): string[] {
  const roots: string[] = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name === "data") continue
    const path = join(dir, entry.name)
    if (entry.isDirectory()) {
      roots.push(...findMarkerRoots(path, marker))
    } else if (entry.isFile() && entry.name === marker) {
      roots.push(normalizePath(dirname(path)))
    }
  }
  return roots.sort()
}

function walkFiles(dir: string): string[] {
  const files: string[] = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name === "data") continue
    const path = join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...walkFiles(path))
    } else if (entry.isFile()) {
      files.push(normalizePath(path))
    }
  }
  return files
}

function domainId(domain: string): string {
  return `domain_${safeId(domain)}`
}

function moduleId(modulePath: string): string {
  return `module_${safeId(modulePath)}`
}

function safeId(value: string): string {
  return value.replace(/[^a-zA-Z0-9_]/g, "_")
}

function escapeLabel(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, "'")
}

function normalizePath(path: string): string {
  return path.replace(/\\/g, "/").replace(/\/$/, "")
}

function stripModulesPrefix(path: string): string {
  return path.startsWith("modules/") ? path.slice("modules/".length) : path
}

function readJson(path: string): JSONRecord {
  return JSON.parse(readFileSync(path, "utf8")) as JSONRecord
}

function asRecord(value: unknown): JSONRecord {
  return value && typeof value === "object" && !Array.isArray(value) ? value as JSONRecord : {}
}

function arrayOfRecords(value: unknown): JSONRecord[] {
  return Array.isArray(value) ? value.map(asRecord) : []
}

function stringArray(value: unknown): string[] {
  return Array.isArray(value) ? value.map(String).filter(Boolean) : []
}

function stringField(value: unknown): string {
  return typeof value === "string" ? value : ""
}
